project:
  type: website
  output-dir: docs

website:
  title: "emmataraburke.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual


  
# ~ additional metadata excluded for brevity ~

