project:
  type: website
  output-dir: docs

website:
  title: "Where's Emma"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: travelpics.qmd
        text: My Travels

format:
  html:
    theme: sketchy
    css: styles.css
    toc: true
    page-layout: full

editor: visual


  
# ~ additional metadata excluded for brevity ~

