---
title: "Backstory"
---

This is a place where I will tell the story of "Wheres Emma?"

That question became a running joke in my family because when I was just born, the first thing my older sister would do was ask "Wheres Emma?!" as soon as she got home from preschool. As an infant, I was usually located within the confines of the household, usually stationary, limited to wherever my parents would carry me.

Nowadays, both my sister and my parents are unconcerned with my whereabouts. Just this past winter I told them I was going to Brazil and they didn't bat an eye or ask any further questions. It is up to me now to answer the unasked question of "Where's Emma?"

When I was seven years old my family decided it would be a good time to take me and my sister on a five week trip to Thailand with our Grandmother who grew up there. While I wish I was a little older to remember everything, this trip really stuck with me. I think the vastly different climate and culture made a lasting impression. It was the most incredible journey I had experienced.

As I got older and gained independence, I started traveling with friends. When I was 13 I went to England with my two best friends and we exercised our independence and autonomy, navigating trains and buses to explore the country (and staying with my friend Daisy's grandparents of course.) Later on I signed up for a youth educational trip to take me back to Thailand and Vietnam, where I met my distant relatives on my Grandmother's side. There I studied access to education in rural settings.

Two years later I did another trip to the Dominican Republic to study public health. This was the first country I went to where I could practice speaking Spanish.

My Spanish skills were cemented when I studied abroad in Chile for three months. It was a wonderful educational experience and the most academically engaged I have ever been. After studying abroad I decided to go on a long trip through Uruguay and Brazil with my friends. We already had experience traveling together in Mexico, so we were ready for another big adventure.

Since being in College, I have been to Mexico, Hawaii, Uruguay, Brazil, and Puerto Rico with a variety of friends. I have learned a lot from traveling with friends. I have gotten to see them pushed to their limits and tested in new settings with new challenges. Sometimes friendships faltered after long exhaustive travel, other times they were strengthened. In any case, I am confident enough in my travel experiences and my language abilities that I am ready to travel alone.

I am ready for solitude. I am ready for adventure. Where will I go next?
